In [38]:
# Number 1
x = list(range( 10,16))

x.reverse()
print(x)

[15, 14, 13, 12, 11, 10]


In [40]:
#Number 2
import numpy as np

x = np.linspace(0, 5, 100)
fifth_element = []

for i in range(0, 5):  
    fifth_element.append(float(x[i]))   

print(every_5th)


[0.0, 0.25252525252525254, 0.5050505050505051, 0.7575757575757576, 1.0101010101010102, 1.2626262626262625, 1.5151515151515151, 1.7676767676767677, 2.0202020202020203, 2.2727272727272725, 2.525252525252525, 2.7777777777777777, 3.0303030303030303, 3.282828282828283, 3.5353535353535355, 3.7878787878787876, 4.040404040404041, 4.292929292929293, 4.545454545454545, 4.797979797979798]


In [77]:
# Number 3

y = np.arange(1, 21).reshape(4,5)   
print(y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [50]:
row_2 = y[1,:]
print(f'second row is {row_1}')

column_1 = y[:,0]
print(f'First Column is {column_1}')

second row is [ 6  7  8  9 10]
First Column is [ 1  6 11 16]


In [72]:
# Number 4

Ages = [
    [28, 22, 24, 25, 18, 32],
    [18, 12, 30, 42, 20, 19],
]

age_numpy = np.array(Ages)
print(age_numpy)



[[28 22 24 25 18 32]
 [18 12 30 42 20 19]]


In [76]:
Transposed_age = np.transpose(age_numpy)
print(f'The Tansposed Matrix is \n {Transposed_age} ')

Diagonals_age = np.diag (age_numpy)
print (f'The Diagonals are {Diagonals_age} ')

matrix_age = age_numpy * 3
print(f'Matrix multiplied by 3:\n {matrix_age} ')



The Tansposed Matrix is 
 [[28 18]
 [22 12]
 [24 30]
 [25 42]
 [18 20]
 [32 19]] 
The Diagonals are [28 12] 
Matrix multiplied by 3:
 [[ 84  66  72  75  54  96]
 [ 54  36  90 126  60  57]] 


In [83]:
#Number 5
Zeros = np.zeros((3,4))   
print(Zeros)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [90]:
Zeros[:, -1] = 1   
print("Array after replacing last column:\n", Zeros)



Array after replacing last column:
 [[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [103]:
# Number 6
import numpy as np

Identity = np.eye(5)
print( Identity)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [106]:
# New diagonal values
new_diag = np.arange(1, 6)

# Replace diagonal
np.fill_diagonal(Identity, new_diag)
print(Identity)



[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [105]:
anti_diag = np.fliplr(Identity).diagonal()
print( anti_diag)


[0. 0. 3. 0. 0.]


In [124]:
#Number 7
array = np.random.randint(1, 51, size=30)  
print(array)

# Numbers less than 20
less_than_20 = array[array >= 20]  
print( f' Numbers Greater than 20 are {less_than_20} ')

odd_num = less_than_20[less_than_20 % 2 != 0] 
print(f'odd numbers are {odd_num} ')

count = odd_num.size  # or len(arr_odd)
print("\nNumber of remaining values:", count)



[23  3 28 19 33 18 39 12 30 10  9 32 35 20 29 17  2 17 49 38 20 40  9  7
 24 48 50 24 16 22]
 Numbers Greater than 20 are [23 28 33 39 30 32 35 20 29 49 38 20 40 24 48 50 24 22] 
odd numbers are [23 33 39 35 29 49] 

Number of remaining values: 6


In [126]:
# Number 8
A= np.arange(1, 13).reshape(3,4)   
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [128]:
added_array = A + np.array([ 10, 20, 30 ,40])
print(added_array)

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [131]:
# Number 9
import numpy as np


vector = np.linspace(1, 10, 10)
print( vector)

print('-------------------------------------------------------------------------------------')
sqrt_vec = np.sqrt(vector)
print( sqrt_vec)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
-------------------------------------------------------------------------------------
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [135]:
# Number 10
mat= np.arange(1,37).reshape(6,6)
print(mat)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [138]:
new_mat = mat.reshape(3,12)
print(new_mat)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]


In [139]:
Original_mat = new_mat.reshape(6,6)
print( Original_mat)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [141]:
Greater_than_20 = Original_mat[Original_mat > 20]  
print( f' Numbers Greater than 20 are {Greater_than_20} ')


 Numbers Greater than 20 are [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36] 


In [142]:
# Number 11


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20])

# Select elements divisible by 2 or 5
filtered = arr[(arr % 2 == 0) | (arr % 5 == 0)]  

print("Elements divisible by 2 or 5 are :\n", filtered)


Elements divisible by 2 or 5 are :
 [ 2  4  5  6  8 10 12 15 20]


In [147]:
# Number 12 

def compute(v):
    """
    Piecewise function:
    f(x) = 2*x       if x > 0
           1 - x     otherwise
    """
    v = np.array(v)
    return np.where(v > 0, 2*v, 1-v)



In [149]:
v = np.array([-2, -1, 0, 1, 2, 3])
result = compute(v)
print(f' f(v) = {result}')


 f(v) = [3 2 1 2 4 6]


In [154]:
# Number 13

R = np.array ([[1 ,3],
              [-1, 7]])
S = np.array ([[5,2],
              [1,2]])

I =np.eye(2)
print(I)

print(R)
print (S)



[[1. 0.]
 [0. 1.]]
[[ 1  3]
 [-1  7]]
[[5 2]
 [1 2]]


In [155]:
R_T = R.T
print(R_T)

[[ 1 -1]
 [ 3  7]]


In [163]:
Results = 2*I + 4*R_T + R @ S
print(Results)

[[14.  4.]
 [14. 42.]]


In [ ]:
def comput (x):
    """
    Piecewise function:
    p(x) = x^4 + 3 * x ^ 2 - 2        at x = 3 *sqrt(2)
          
    """
    x = 3 * np.sqrt(2)

    

In [168]:


x = 3 * np.sqrt(2)

# Define polynomial coefficients for p(x) = -x^4 + 3*x^2 - 2
coeffs = [-1, 0, 3, 0, -2]

# Evaluate the polynomial at x
p_val = -x**4 + 3*x**2 - 2

# Compute the roots of the polynomial
roots = np.roots(coeffs)

# Print results
print("Polynomial p(x) at x = 3√2:", p_val)
print("Roots of the polynomial:", roots)


Polynomial p(x) at x = 3√2: -272.00000000000017
Roots of the polynomial: [-1.41421356 -1.          1.41421356  1.        ]
